---
- name: add repository
  command: export PKG_PATH=http://kartolo.sby.datautama.net.id/OpenBSD/6.3/packages/amd64/

- name: Make sure listed package installed
  openbsd_pkg:
    name: "{{item}}"
    state: present
  wiht_items:
    - nginx
    - php
    - php-mysqli
    - mariadb-server

- name: copy config for nginx
  template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
