---
- name: star mysql_install_db after mariadb installation
  shell: mysql_install_db

- name: set root default password
  mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{new_root_password}}"
      check_implicit_admin: yes
      login_user: root
      login_password: "{{ root_pwd }}"
      state: present
  with_items:
      - 127.0.0.1
      - localhost
