---
- name: add repository
  command: export PKG_PATH=http://kartolo.sby.datautama.net.id/OpenBSD/6.3/packages/amd64/

- name: Make sure listed package installed
  openbsd_pkg:
    name: "{{item}}"
    state: present
  wiht_items:
    - nginx
    - php
    - php-mysqli
    - mariadb-server

- name: star mysql_install_db after mariadb installation
  command: mysql_install_db

- name: set root default password
  mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{new_root_password}}"
      check_implicit_admin: yes
      login_user: root
      login_password: "{{ root_pwd }}"
      state: present
  with_items:
      - 127.0.0.1
      - localhost

- name: copy config for nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Enable and start service
  command: "{{item}}"
  with_items:
    - rcctl enable nginx && rcctl start nginx
    - rcctl enable php70_fpm && rcctl start php70_fpm
    - rcctl enable mysqld  && rcctl start mysqld
